# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 13:02
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('area', models.IntegerField()),
                ('layout', models.CharField(max_length=20)),
                ('floor', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('building_type', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=20)),
                ('parking', models.BooleanField()),
                ('price_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('mgmt_fee', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('balcony', models.BooleanField()),
                ('pet', models.BooleanField()),
                ('cook', models.BooleanField()),
                ('mrt', models.BooleanField()),
                ('tv', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('ref', models.BooleanField()),
                ('water_hearter', models.BooleanField()),
                ('natural_gas', models.BooleanField()),
                ('cabel_tv', models.BooleanField()),
                ('network', models.BooleanField()),
                ('wash_machine', models.BooleanField()),
                ('bed', models.BooleanField()),
                ('wardrobe', models.BooleanField()),
                ('table', models.BooleanField()),
                ('sofa', models.BooleanField()),
                ('chair', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
