# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0008_auto_20171002_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='who_likes',
            field=models.ManyToManyField(blank=True, related_name='who_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
