# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
