# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20171026_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.CharField(blank=True, default='http://www.gravatar.com/avatar?d=mm', max_length=200),
        ),
    ]
